### ISSUE TITLE
Nevalidní certifikát

### ISSUE THREAD

**Issue by matyx** [fitak/fitak#74]
Na webu expiroval certifikát, bylo by fajn tam nahodit aktuální

**Comment by tajo** [comment]
@JanTvrdik @Mikulas nechce se mi to moc resit, vidite jeste nejak realne release nove verze?

**Comment by Mikulas** [comment]
Je to naprosto nereálné, resp. „snažíme“ se na to asi tak 8 měsíců. :/ Ale jestli můžeš nazdílet přístup na vps tak to vyřeším.

**Comment by tajo** [comment]
@Mikulas ok :-( vyresim to sam...

**Comment by tajo** [comment]
Zrusil jsem certifikat uplne a vyhodil redirect z https na http (beztak se na fitakovi neodehrava zadna zasadni komunikace). Akorat se mi nepovedlo udelat redirect z https na http (bezi tam Apache). Dal jsem tomu 20min, vic tomu obetovat nehodlam.

**Comment by matyx** [comment]
Teď fiťák nejede pro jistotu vůbec :(

**Comment by Mikulas** [comment]
Mě jde, akorát musíš na http://www.fitak.cz/ (ne https://www.fitak.cz/)

**Comment by matyx** [comment]
To jsem dal, ale přesměruje mě to na https

**Comment by tajo** [comment]
Nedela ti to nejakej doplnek prohlizece? To presmerovani bylo v nette routeru a je uz pryc.

**Comment by matyx** [comment]
Asi to firefox cachuje, v anonymním prohlížení to je OK.
