### ISSUE TITLE
Přidat node_modules, composer atp. do .gitignore

### ISSUE THREAD

**Issue by tenhobi** [fitak/fitak#80]
Věci jako _node_modules_ či balíčky z _composeru_ by neměly (dle mého) být ponéchávány v repozitáři, jelikož verzovat "služby", které už jsou verzovány je značně nevhodné a neefektivní. 

Všechny tyto balíčky/moduly se mohou (resp. by se měly) aktualizovat, což znamená že při každé aktualizaci se musí přidat nová verze i v tomto projektu.

Jelikož se dají nainstalovat za pár sekund, doporučoval bych je přidat do `.gitignore`.

**Comment by Mikulas** [comment]
To je záměrně a vedli jsme o tom hodinové diskuze, nejenom u tohohle projektu. Mimo jiné to jak to je teď usnadňuje deploy a–což je výhoda hlavně u npm–nejsme závislí na tom, že ty balíčky v budoucnu někdo přestane hostovat.

Za mě wontfix.

**Comment by tenhobi** [comment]
Chápu. Má to své plusy i mínusy, dle mého převažují plusy, ale je to váš projekt. :-)
