### ISSUE TITLE
Přidat EditorConfig

### ISSUE THREAD

**Issue by tenhobi** [fitak/fitak#81]
Bylo by vhodné sjednotit velikost odsazení (+ používat mezery, ne taby), poslední řádek volný, trailing mezery apod. 

Doporučuji http://editorconfig.org, který má velkou podporu v nejrůznějších editorech či IDE, který zajišťuje nastavení editoru z tohoto souboru. 

Nastavení takového konfiguračního souboru se dá provést jednoduše v souboru `.editorconfig` viz http://editorconfig.org/#example-file.

**Comment by Mikulas** [comment]
Díváš se na dev branch? Jestli tam jsou nějaké nesrovnalosti, klidně pošli PR. Jinak všichni jsme používali phpstorm, a ten defaultně editor config nepodporuje (ale je to na plugin).

**Comment by tenhobi** [comment]
Ano, koukal jsem na dev branch. Např. pro odsazování je na většině místech použit tab, ale sem tam jsem viděl využité 2 či 4 mezery. Koncové řádky a trainling mezery jsou ale jak koukám skoro všude. :-) 

Na PR teď nemám bohužel moc času. Řeším maturitu a pracuji na mém projektu. Třeba jednou. :smile_cat: Šlo mi hlavně o to, když využíváte automatizační nástroje jako gulp atp., že by bylo vhodné "zautomatizovat" i nastavení editorů.
